import type { Request, Response } from 'express';
import { getMysqlPool, getPgPool, createSSHTunnel } from '../services/database';
import type { SSHConfig } from '../types';

interface DatabaseRequest {
  dbType?: 'mysql' | 'postgresql' | 'sqlite';
  host?: string;
  port?: number;
  user?: string;
  password?: string;
  database?: string;
  ssh?: SSHConfig;
}

interface ExportRequest extends DatabaseRequest {
  tables?: string[];
  format?: 'sql' | 'json' | 'csv';
}

// 获取最终连接配置
async function resolveConnection(req: DatabaseRequest) {
  const { host, port, ssh } = req;
  
  if (ssh?.enabled && host && port) {
    const tunnel = await createSSHTunnel(ssh, host, port);
    return { finalHost: '127.0.0.1', finalPort: tunnel.localPort };
  }
  
  return { finalHost: host || 'localhost', finalPort: port || 3306 };
}

// POST /api/export - 导出数据库
export async function exportDatabase(req: Request, res: Response): Promise<void> {
  try {
    const body = req.body as ExportRequest;
    const { dbType = 'mysql', user = '', password = '', database, tables, format = 'sql', ssh } = body;
    const conn = await resolveConnection(body);
    
    if (dbType === 'mysql') {
      const pool = await getMysqlPool({ 
        host: conn.finalHost, 
        port: conn.finalPort, 
        user, 
        password, 
        database 
      });
      
      // 获取表结构
      const [tableNames] = await pool.query(`
        SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = ?
      `, [database]);
      
      let dump = `-- Database: ${database}\n-- Generated by DBForge\n\n`;
      
      for (const t of tableNames as any[]) {
        const tableName = t.TABLE_NAME;
        
        // 表结构
        const [createTable] = await pool.query(`SHOW CREATE TABLE \`${tableName}\``);
        dump += `\nDROP TABLE IF EXISTS \`${tableName}\`;\n`;
        dump += (createTable as any)[0]['Create Table'] + ';\n';
        
        // 数据
        if (format === 'sql') {
          const [rows] = await pool.query(`SELECT * FROM \`${tableName}\``);
          for (const row of rows as any[]) {
            const values = Object.values(row).map((v: any) => {
              if (v === null) return 'NULL';
              return typeof v === 'string' ? `'${v.replace(/'/g, "''")}'` : v;
            }).join(', ');
            if (values) {
              dump += `INSERT INTO \`${tableName}\` VALUES (${values});\n`;
            }
          }
        }
      }
      
      res.setHeader('Content-Type', 'text/plain; charset=utf-8');
      res.setHeader('Content-Disposition', `attachment; filename="${database}.sql"`);
      res.send(dump);
    } else if (dbType === 'postgresql') {
      const pool = getPgPool({ 
        host: conn.finalHost, 
        port: conn.finalPort, 
        user, 
        password, 
        database 
      });
      
      let dump = `-- Database: ${database}\n-- Generated by DBForge\n\n`;
      
      // 获取表
      const tablesResult = await pool.query(`
        SELECT table_name FROM information_schema.tables 
        WHERE table_schema = 'public' AND table_type = 'BASE TABLE'
      `);
      
      for (const t of tablesResult.rows) {
        const tableName = t.table_name;
        
        // 表结构
        const schemaResult = await pool.query(`
          SELECT pg_get_create_table_statement('${tableName}') as create_stmt
        `).catch(() => ({ rows: [{ create_stmt: '' }] }));
        
        dump += `\nDROP TABLE IF EXISTS "${tableName}";\n`;
        dump += schemaResult.rows[0]?.create_stmt || '';
        
        // 数据
        if (format === 'sql') {
          const dataResult = await pool.query(`SELECT * FROM "${tableName}"`);
          for (const row of dataResult.rows) {
            const values = Object.values(row).map((v: any) => {
              if (v === null) return 'NULL';
              return typeof v === 'string' ? `'${v.replace(/'/g, "''")}'` : JSON.stringify(v);
            }).join(', ');
            if (values) {
              dump += `INSERT INTO "${tableName}" VALUES (${values});\n`;
            }
          }
        }
      }
      
      res.setHeader('Content-Type', 'text/plain; charset=utf-8');
      res.setHeader('Content-Disposition', `attachment; filename="${database}.sql"`);
      res.send(dump);
    } else {
      res.status(400).json({ success: false, message: '不支持的数据库类型' });
    }
  } catch (error: any) {
    res.status(400).json({ success: false, message: error.message });
  }
}

// POST /api/backup - 备份
export async function backup(req: Request, res: Response): Promise<void> {
  try {
    const body = req.body as DatabaseRequest;
    const { dbType = 'mysql', user = '', password = '', database, ssh } = body;
    const conn = await resolveConnection(body);
    
    if (dbType === 'mysql') {
      const pool = await getMysqlPool({ 
        host: conn.finalHost, 
        port: conn.finalPort, 
        user, 
        password, 
        database 
      });
      
      // 备份逻辑
      const [tables] = await pool.query(`
        SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = ?
      `, [database]);
      
      const backupData: Record<string, any[]> = {};
      
      for (const t of tables as any[]) {
        const [rows] = await pool.query(`SELECT * FROM \`${t.TABLE_NAME}\``);
        backupData[t.TABLE_NAME] = rows as any[];
      }
      
      res.json({ success: true, backup: backupData, timestamp: new Date().toISOString() });
    } else {
      res.status(400).json({ success: false, message: '仅支持MySQL备份' });
    }
  } catch (error: any) {
    res.status(400).json({ success: false, message: error.message });
  }
}
